apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app-container
          image: pritammehta/angular-app:latest   # using your Docker Hub image
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  selector:
    app: angular-app
  type: NodePort   # change to LoadBalancer for cloud
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30030   # optional — you can remove to auto-assign
